site_name: {{ cookiecutter.project_slug }}
site_url: https://{{ cookiecutter.github_user }}.github.io/{{ cookiecutter.project_slug }}/
site_author: {{ cookiecutter.author }}
site_description: shortdesc
copyright: Copyright &copy; 2023 {{ cookiecuter.author }}
repo_url: https://github.com/{{ cookiecutter.github_user}}/{{ cookiecutter.project_slug}}
repo_name: {{ cookiecutter.github_user }}/{{ cookiecutter.project_slug }}
edit_uri: edit/main/docs/

theme:
  # logo: assets/white-spatula.svg
  name: material
  palette:
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

  features:
    #- navigation.tabs
    - navigation.sections
    - navigation.top
    - content.tabs.link
  icon:
    repo: fontawesome/brands/github
markdown_extensions:
  - admonition
  - def_list
  - pymdownx.highlight
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
  - mkdocs-click
  - toc:
      permalink: true
plugins:
  - search

extra_css:
  - assets/extra.css
nav:
  - "index.md"
  - Reference:
      - "cli.md"
      - "reference.md"
  - About:
      - "contributing.md"
      - "code_of_conduct.md"
      - "changelog.md"
