install-base:
	poetry add --dev pytest pytest-cov black mkdocs-material ruff mypy
	poetry add structlog
	{% if cookiecutter.cli == 'typer' -%}poetry add typer{% endif %}

test:
	poetry run pytest --cov=src/ --cov-report html

lint:
	poetry run ruff src/ tests/
	poetry run ruff format src/ tests/

docs:
	poetry run mkdocs serve

release type:  # patch, minor, major
	poetry version {{ '{{' }}type}}
	poetry build
	poetry run mkdocs gh-deploy
	poetry publish
	git commit -am "release $(poetry version -s)"
	git tag v$(poetry version -s)
	git push
	git push --tags
	gh release create v$(poetry version -s) -F docs/changelog.md
